In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('MODEL_DATA_2.csv')
print(len(dataset))
dataset.drop_duplicates(inplace=True)
print(len(dataset))
X = dataset.iloc[:, 4:-1].values
y = dataset.iloc[:, -1].values

1999
775


In [3]:
y = y.reshape(len(y),1)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [6]:
print(X_train)

[[ 0.         -1.04009079  0.77793259 -0.89601688]
 [ 0.          0.98775918 -1.28767    -0.89601688]
 [ 0.         -0.02616581  0.77793259  1.26347958]
 ...
 [ 0.         -1.04009079 -1.28767    -0.89601688]
 [ 0.         -1.04009079  0.77793259 -0.89601688]
 [ 0.          0.98775918  0.77793259 -0.89601688]]


In [7]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

C:\Users\pratik\anaconda3\envs\salary_sense\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [11]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[2,2.5,3,1]])))

array([563947.09])

In [9]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[563517.61 580000.  ]
 [493471.27 540000.  ]
 [578612.13 589999.5 ]
 [216416.51 200000.  ]
 [493471.27 480000.  ]
 [391491.99 600000.  ]
 [216468.52 200000.  ]
 [612092.88 585000.  ]
 [568589.35 585000.  ]
 [226238.14 100000.  ]
 [216416.51 200000.  ]
 [493471.27 439999.5 ]
 [612092.88 585000.  ]
 [493471.27 535000.  ]
 [493471.27 530000.  ]
 [391491.99 569999.5 ]
 [331442.57 450000.  ]
 [612092.88 585000.  ]
 [612092.88 585000.  ]
 [343576.74 200000.  ]
 [391491.99 605000.  ]
 [493471.27 320000.  ]
 [493471.27 384999.5 ]
 [216416.51 200000.  ]
 [216447.41 200000.  ]
 [493471.27 415000.  ]
 [391491.99 200000.  ]
 [216447.41 200000.  ]
 [493471.27 435000.  ]
 [301468.41 200000.  ]
 [216447.41 200000.  ]
 [216447.41 615000.  ]
 [493471.27 594999.5 ]
 [216447.41 200000.  ]
 [563517.61 580000.  ]
 [476418.22 670000.  ]
 [216468.52 200000.  ]
 [391731.35 215000.  ]
 [497274.86 589999.5 ]
 [344363.67 350000.  ]
 [493471.27 545000.  ]
 [568589.35 475000.  ]
 [568589.35 585000.  ]
 [563517.61

In [10]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6408135566470984